### ISSUE TITLE
Yank form_data gems

### ISSUE THREAD

**Issue by sferik** [httprb/form_data.rb#3]
I accidentally used the [`form_data` gem instead of `http-form_data`](https://github.com/sferik/twitter/commit/33847d257bfe1089f582f730b635a3fcf041c702). I’m suggest you yank all version of `form_data`, so others don’t make the same mistake.

**Comment by ixti** [comment]
Oh. Sorry. Will do.

**Comment by ixti** [comment]
Yanked all version. Sorry for that confusion once again.

**Comment by benlovell** [comment]
I think this is the cause of the issues i'm seeing now whilst trying to bundle a locked version of the `http` gem. I'm putting together a repro.

**Comment by sferik** [comment]
@benlovell What versions of Bundler are you using? I thought that modern versions of Bundler would install yanked gems if they were part of a `Gemfile.lock`. /cc @indirect

**Comment by benlovell** [comment]
@sferik Bundler 1.7.9 appears be installing the locked gem as expected, when it's present on the machine but still, something untoward is happening with the gem `specs`... I'll report this over at HTTP.

**Comment by benlovell** [comment]
@sferik actually, after updating bundler to latest on travis this worked out fine. I couldn't reproduce this locally either using travis' version of bundler - 1.7.9. 

My apologies folks <3, it seems like a travis issue.

**Comment by ixti** [comment]
Actually yanking all versions caused one unexpected problem. I have completely forgot that `http` gem 0.7.X had it as dependency (thanks @tarcieri for bringing that up). I have released `http 0.7.2` recently with appropriate fix.
